### ISSUE TITLE
Tidy up Docker image

### ISSUE THREAD

**Issue by etienne-napoleone** [s0md3v/Photon#101]
I made some change to the docker image.
- Don't clone the repo, just `COPY` the files.
- Two step `COPY` to avoid running `pip install` on each build if requirements.txt hasn't changed (layer caching).
- Tidied up the `WORKDIR`.

It brings down the size of the image to 87.5 MB while being a lot faster to build.

I updated in consequence:
- `.travis.yml`: add python 3.7 as it's the version used by the docker image (`python:3-alpine`).
- `readme.md`: updated the Docker chapter.

Although I read in the contribution guidelines that non-code related PRs will not be merged. So here's my issue!
You can check my changes at [etienne-napoleone/Photon](https://github.com/etienne-napoleone/Photon).

**Comment by s0md3v** [comment]
Honestly, I don't have much experience with docker but a friend of mine who also uploaded the exisiting image, told me that it doesn't worth it.
`git clone` method is fine and `10 MB` doesn't make much difference and isn't worth the hassle either.

So I am closing it.

**Comment by etienne-napoleone** [comment]
Ok!
Actually the size is the smallest argument and maybe I didn't reflected it correctly.
I'd say that the main point is the build process.
The flaws I see with using git:
- Forks have to update the Dockerfile for it to work with their repo
- The source code is literally already here, why would you install a dependency and pull the code from the internet?
- If you want to test a local change or even a feature branch change... well you can't without changing the Dockerfile, as it needs to be on the default branch of your git repo
 
 Also, the build time:

Dockerfile | First build (no cache) | Next build
------------ | ------------ | -------------
Old | 1m 12s | 47s
New | 54s | 14s

The build time is divided by almost 4 on cached build.

Anyway, thanks for your tools :) I have a good time using it and that's why I thought about helping with the image.
