### ISSUE TITLE
Unneeded f.close() instructions

### ISSUE THREAD

**Issue by brunobord** [s0md3v/Photon#11]
That's a small one I've spotted browsing your code...

Considering [the following block of code](https://github.com/s0md3v/Photon/blob/master/photon.py#L366-L369):
```python
with open('%s/links.txt' % name, 'w+') as f:
    for x in storage:
        f.write(x + '\n')
f.close()
```

the `f.close()` instruction is redundant, because if you're using the `with` statement, the file is already closed, as shown in the Python documentation: https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files

```python
>>> with open('workfile') as f:
...     read_data = f.read()
>>> f.closed
True
```

**Comment by s0md3v** [comment]
Thanks for this one.
I learned something new today ^_^
