### ISSUE TITLE
NameError: global name 'threading' is not defined

### ISSUE THREAD

**Issue by Fultos** [s0md3v/Photon#112]
└──╼ $python photon.py -u "https://mydomain.com" --dns
      ____  __          __
     / __ \/ /_  ____  / /_____  ____
    / /_/ / __ \/ __ \/ __/ __ \/ __ \
   / ____/ / / / /_/ / /_/ /_/ / / / /
  /_/   /_/ /_/\____/\__/\____/_/ /_/ v1.2.1

[+] URLs retrieved from robots.txt: 32
[~] Level 1: 34 URLs
Traceback (most recent call last):
  File "photon.py", line 284, in <module>
    flash(extractor, links, thread_count)
  File "/home/user/Downloads/Tools/Photon/core/flash.py", line 38, in flash
    threader(function, splitted)
  File "/home/user/Downloads/Tools/Photon/core/flash.py", line 18, in threader
    task = threading.Thread(target=function, args=(url,))
NameError: global name 'threading' is not defined

Do I need to fix the code ot there is something I did wrong?

**Comment by s0md3v** [comment]
Can you verify if the fix works?

**Comment by Fultos** [comment]
Hey! It works like a charm!!!
Thanks a lot s0md3v, looking forward to your future work :)
