### ISSUE TITLE
I tried using it with the python3 doesn't work

### ISSUE THREAD

**Issue by fr33s0ul** [s0md3v/Photon#114]
<pre>sudo python3 photon.py 
Traceback (most recent call last):
  File &quot;photon.py&quot;, line 23, in &lt;module&gt;
    from core.zap import zap
  File &quot;/pentest/Photon/core/zap.py&quot;, line 4, in &lt;module&gt;
    from core.utils import verb, xmlParser
  File &quot;/pentest/Photon/core/utils.py&quot;, line 2, in &lt;module&gt;
    import tld
ModuleNotFoundError: No module named &apos;tld&apos;
</pre>

**Comment by s0md3v** [comment]
Install the module `tld`

**Comment by fr33s0ul** [comment]
thank you! I tried before to install it, but I forgot to use the pip3 in the installation

**Comment by 0x4rk0** [comment]
Had issues with pip3 after installing it...

```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py --force-reinstall
sudo pip3 install tld
``` 

This solved the issue for me.
