### ISSUE TITLE
Exceptions in threads during scanning in Level 1 & 2

### ISSUE THREAD

**Issue by 4k4xs4pH1r3** [s0md3v/Photon#120]
Exception in thread Thread-4694:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "photon.py", line 211, in extractor
    if is_link(link, processed, files):
  File "/usr/share/Photon/core/utils.py", line 41, in is_link
    is_file = url.endswith(BAD_TYPES)
TypeError: endswith first arg must be str, unicode, or tuple, not list

![image](https://user-images.githubusercontent.com/32862241/53689769-23802700-3d2b-11e9-8f84-94f6ad8a311b.png)

**Comment by s0md3v** [comment]
I am unable to reproduce the issue, would it be possible to share the website you were crawling?
Thanks.

**Comment by TerrorFactor** [comment]
Had the same issue with multiple sites, even with just `-u="google.com"`
It does seem to happen only on python 2, python 3 is ok.

**Comment by s0md3v** [comment]
Looks like you are using a large number of threads or your network connection is not very fast.
Please use a higher value of `timeout` as follows

`python photon.py -u "http://example.com --timeout=20`

The default `timeout` value is 6.

**Comment by TerrorFactor** [comment]
Seems unlikely. From speedtest.net: ping = 0 ms, download = 885 mbps, upload = 939 mbps.
Threads is default (not specified), adding "--timeout=20"  doesn't help. Tried also with --timeout=2000, also no effect.

Using Python 2.7.15+ on Ubuntu in Windows Subsytem for Linux.

**Comment by s0md3v** [comment]
That's strange. I had a half mind about dropping support for python 2. Looks like it needs to be done.

**Comment by TerrorFactor** [comment]
That's one way of course. It would definitely be more clear.
