### ISSUE TITLE
just some ideas

### ISSUE THREAD

**Issue by digitalist** [s0md3v/Photon#14]
collecting of  /ads.txt
and https:// certs info  

may be useful

**Comment by s0md3v** [comment]
Thanks for the suggestions, I really appreciate it but I have two questions to ask :')

1. How do you find out if a javascript file runs ads?
2. Don't you think that falls out of the scope of a crawler program.

**Comment by s0md3v** [comment]
It's not about the difficulty of implementation, it's about relevance. A crawler isn't supposed to check SSL certificates.

**Comment by digitalist** [comment]
but as a crawler it CAN check/grad for their presence as an important meta

**Comment by s0md3v** [comment]
Sorry but I am closing this issue, I don't think it's relevant at all.

1. ads.txt isn't that common
2. Grabbing SSL certificates is out of scope

Thanks for the suggestions tho, let me know if you have some more ^_^
