### ISSUE TITLE
Fancy windows development

### ISSUE THREAD

**Issue by monodrone** [s0md3v/Photon#141]
The git pull, gets the Windows    ^M     line-ends version.
I need to do dos2unix to clean it while others may be stuck on failed executions from exported terminal bins in PATH. 

It requires explicit python interpreter calling instead of using

     #!/usr/bin/env python3
     or
     #!/usr/bin/python3
    
Henceforth,   exporting my     PATH=/hack/bins/            would fail.
    ./photon.py          

Please always save  clean  UNIX    format!

**Comment by speedmann** [comment]
exorting `PATH=/hack/bins` is always a bad idea.

Using `#!/usr/bin/env python3` is the correct way of getting the python executeable and should always be done.

Also, on any system which is correctly configured, the `^M` should not cause any issues. I tested several systems now and had no issues with this.
