### ISSUE TITLE
Add Scrapoxy support for API

### ISSUE THREAD

**Issue by fabienvauchelles** [s0md3v/Photon#15]
Hello,

If you want a free & opensource proxies network, you can add proxy support for Scrapoxy (http://scrapoxy.io/)

Keep me in touch if you're interested :)

Fabien.

**Comment by s0md3v** [comment]
If you are reading this, I need your help to implement this.
I am already working on a lot of things and I am way too tired and sleep deprived to go through the API docs.
Thanks in advance :heart:
