### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by xavier1395** [s0md3v/Photon#150]
I get this error when trying to map dns information

File "photon.py", line 414, in <module>
    dnsdumpster(domain, output_dir)
  File "/Users/.../Photon/plugins/dnsdumpster.py", line 11, in dnsdumpster
    r"name='csrfmiddlewaretoken' value='(.*?)'", response).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by formyosint** [comment]
I've the same error
