### ISSUE TITLE
No ninja mode??

### ISSUE THREAD

**Issue by 0xm00n** [s0md3v/Photon#169]
I was running photon and tried to run ninja mode, but apparently its an unrecognized argument.
someone know what's happening?

**Comment by bgagan911** [comment]
same here

**Comment by jurdajrd** [comment]
@0xm00n Ninja mode was removed in release numver 1.3.0.
![image](https://user-images.githubusercontent.com/54391873/123774906-2923b280-d8ce-11eb-9963-d7c07691cf33.png)
