### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by trixi93** [s0md3v/Photon#17]
App crash and show this error: "UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 17: ordinal not in range(128)"
<img width="848" alt="captura de pantalla 2018-07-24 a las 19 53 27" src="https://user-images.githubusercontent.com/7291983/43156755-454b89dc-8f7b-11e8-9d80-71e42f0001c3.png">

**Comment by s0md3v** [comment]
This issue has been fixed already as discussed in #16
Please download the latest version and try again.
Thanks ^_^
