### ISSUE TITLE
Add a mapping file

### ISSUE THREAD

**Issue by Mitsu66** [s0md3v/Photon#20]
Hi,
First, good job !

Is it possible to build a new txt files with all linking informations.

Something like this : 

Source \t Target \t Type \t Nofollow
http://ndd.tld/A \t http://ndd.tld/B \t AHREF \t TRUE
http://ndd.tld/A \t http://ndd.tld/B.jpg \t AHREF \t TRUE

The prupose 

The purpose is to have an idea of how pages are related between them in the website.

**Comment by s0md3v** [comment]
Hi there,

Thanks for the suggestion but why would you need a file with such data? Is there any popular program which processes such data to do something productive?

I am not sure if this is what you want to achieve but I am already working on a plugin that would plot a graph between webpages that are related to each other.

I will be using my own data visualization framework [Quark](https://github.com/s0md3v/Quark) for this purpose and the plotted graph will look something this:

![graph demo](https://camo.githubusercontent.com/e1e11f0ed478f7776ac56422118cd6bca722c770/68747470733a2f2f696d6167652e6962622e636f2f65664752366f2f53637265656e73686f745f323031385f30375f31305f32315f32335f31332e706e67)

Thanks again ^_^

**Comment by Mitsu66** [comment]
Hi,

in fact, i'm looking for a job, we use crawlers (like Screaming Frog).

For example, this kind of matrix can help me to list all URLs which link 404 URLs or something like that to recomand my client to fix all thoses links.
Also, i have a program which calculates pagerank from each of these pages of this kind of matrix, with this information, i know what page needs more links or not to optimize internal linking and improve rankings.

I prefer command line crawlers instead of desktop programs which are to heavy.
To use your program in my job, I just miss the connection between different elements.

By example, i can use "-r" to get titles from all pages but do not have the relationship between a page and its title. At the same way, i have all links but can not know which url links other one.

I understand that this program is not made in a way, but I think that it can be used in my job. Sometimes, can i contact you to understand your code if i want to customize it? Because Python is not the language which i have the better skills but i can try =).
