### ISSUE TITLE
Multithreading question 

### ISSUE THREAD

**Issue by deadbits** [s0md3v/Photon#30]
The approach of splitting the list is a good method as explained in your README, but wouldn't a Queue accomplish the same thing without all the list splitting stuff? You'd still only access unique items across workers.

J/w if there's a reason why you didn't do this as I was going to put in a PR for this exact thing but won't bother if you aren't doing it for some reason 

Thanks!

**Comment by s0md3v** [comment]
Closing this for now, let me know if you have any more questions.
