### ISSUE TITLE
Lines incorrectly stored in text file.

### ISSUE THREAD

**Issue by wzulfikar** [s0md3v/Photon#32]
OS: macOS High Sierra
Python version: Python 3.6.6

So, I tried photon-ing twitter and the output format wasn't what I expected. Or, did I miss something?

Actual output (the `\n` is not processed):
![screen shot 2018-07-29 at 12 02 57 am](https://user-images.githubusercontent.com/7823011/43358400-a75615d4-92c3-11e8-92e1-ca09ff2b4f76.jpg)

Expected output:
![screen shot 2018-07-28 at 11 47 02 pm](https://user-images.githubusercontent.com/7823011/43358402-ac1f24ac-92c3-11e8-8405-00d5c489ff00.jpg)

**Comment by s0md3v** [comment]
It is to let you know that the issue has been acknowledged and being worked on.

**Comment by s0md3v** [comment]
is this the `links.txt` file or `intel.txt`?

**Comment by wzulfikar** [comment]
Can't remember correctly. But it should be the `links.txt`. Btw, I created PR #33 to put more elaboration on the issue.

**Comment by s0md3v** [comment]
Thanks a lot bruh :heart:

**Comment by wzulfikar** [comment]
Ma pleasure bruh 🤗
