### ISSUE TITLE
deleting output directory is dangerous

### ISSUE THREAD

**Issue by sethsec** [s0md3v/Photon#34]
right now, if the user specifies -o /root, won't the program recursively delete /root because it exists (line 640).  

That is why in my pull i changed the w+ to w and only modified the files you wrote in the first place.   

I suggest removing the part about recursively removing the directory structure, and instead, just overwrite your files if the tools is run twice.

**Comment by s0md3v** [comment]
If the user enters `-o /root`, Photon will create a new directory in the current directory with the name `root`.

The logic used to create directories is:
`the_directory_from_which_photon_was_run + '/' + new_directory`

So even if you are running it from root, the directory that will be deleted is `/root/root`

**Comment by s0md3v** [comment]
This issue has been addressed in https://github.com/s0md3v/Photon/commit/a331acdfce8067f6e730c3343197d66251521a05 .


Now if the output directory exists, Photon will simply create (can overwrite) new files for saving in it.
If the output directory doesn't exists, it will be created.

Thanks for contributing ^_^
