### ISSUE TITLE
clear definition of -u

### ISSUE THREAD

**Issue by laoshaw** [s0md3v/Photon#36]
what's the differences among:

```
-u example.com
-u www.example.com
-u http://example.com
-u https://example.com
-u http://www.example.com
-u https://www.example.com
```

looks like their output are all saved under the same example.com/ directory but the content will be different for each case?

**Comment by s0md3v** [comment]
### Domains
`example.com` is domain name, it is the website's identity which makes it different from `example1.com` or `example2.com`.

### Sub-domains
`www.example.com` is a subdomain. You can create as many as subdomains you want on a domain and people use it keep their stuff separated. For example, I may publish my blog at `blog.example.com`, host my ftp server at `ftp.example.com` and the main website at `www.example.com`.

### URLs
`http://` & `https://` are URL schemas and every URL must have one.
`https://` is just a secure version of `http://`.
