### ISSUE TITLE
Can't run photon outside of Photon directory

### ISSUE THREAD

**Issue by sethsec** [s0md3v/Photon#44]
This is the issue if you call the script from /home for instance: 

![image](https://user-images.githubusercontent.com/1268152/43678977-f5d1e932-97ea-11e8-8178-6c8d93928da8.png)

The two lines highlighted in hello are (print(os.getcwd()) and print(sys.path[0]) respectively.  As you can see, the second line is what will make the script work if you call it from anywhere.  

Fix:  on line 182: https://github.com/s0md3v/Photon/blob/master/photon.py#L182
Change:
```with open(os.getcwd() + ```
to:
```with open(sys.path[0] + ```

questions?

**Comment by s0md3v** [comment]
Thanks a lot :heart:
