### ISSUE TITLE
Generating invalid external links

### ISSUE THREAD

**Issue by Miladbr** [s0md3v/Photon#45]
https://github.com/s0md3v/Photon/blob/73e953819b686875a540da1a10be0c02d3f318aa/photon.py#L361

If a website use protocol relative URL (//example.com/foo), Photon mistakenly detect internal links as external. To fix it you can compare links based on netloc, for example:
change:
```
if link.startswith(main_url):
```
to:
```
if urlparse(link).netloc == urlparse(main_url).netloc:
```
Also consider that in case of www sub-domain, same thing may happen.

**Comment by s0md3v** [comment]
I have confirmed the bug but the patch you have suggested considerably slows down Photon
I am trying to find a way to solve it without affecting the performance.
Thanks for pointing it out.

**Comment by s0md3v** [comment]
Hi there,

A fix has been applied, can you confirm that it works?

Thanks.

**Comment by Miladbr** [comment]
Yes, this patch fixed the bug.
