### ISSUE TITLE
Python logic error using 'or'

### ISSUE THREAD

**Issue by cclauss** [s0md3v/Photon#48]
https://github.com/s0md3v/Photon/blob/master/photon.py#L313 does not work as expected.

$ __python3 -c "print('a' or 'e' or 'i' or 'o' or 'u')"__ --> __a__

By or-ing these things together we are only getting the first _Truthy_ which is __a__ or __.png__ on line 313.

**Comment by s0md3v** [comment]
It works as expected.
If any of the conditions is satisfied, `False` is returned.

**Comment by s0md3v** [comment]
Thanks for pointing that out, I fixed it ^_^

**Comment by cclauss** [comment]
https://github.com/s0md3v/Photon/blob/master/photon.py#L478 also

**Comment by s0md3v** [comment]
That's perfectly fine ig
