### ISSUE TITLE
DNS Plantext Output

### ISSUE THREAD

**Issue by Clutchisback1** [s0md3v/Photon#63]
Request for DNS plaintext output:

I was wondering if there could be an enhancement for having Photon spit out the DNS enumerated hostnames to accompany the beautiful image that it produces. This thing is great for sub-domain mapping but typing them out is a pain...

Great product!
![spelling](https://user-images.githubusercontent.com/6752796/44552778-5355ce80-a6f9-11e8-8058-2c3fc65e72ea.jpg)

**Comment by s0md3v** [comment]
Hi there,

Photon now saves subdomains in `subdomains.txt` when [--dns](https://github.com/s0md3v/Photon/wiki/Usage#dumping-dns-data) option is used.
Let me know if you have any other suggestions.

Regards

**Comment by Clutchisback1** [comment]
Oh dope! I love this app man...
