### ISSUE TITLE
python is not suitable for multi thread(because of the GIL) I think you should use multi process 

### ISSUE THREAD

**Issue by xiaosongdhls** [s0md3v/Photon#68]
####
# This function starts multiple threads for a function
####
```
def threader(function, *urls):
    threads = [] # list of threads
    urls = urls[0] # because urls is a tuple
    for url in urls: # iterating over urls
        task = threading.Thread(target=function, args=(url,))
        threads.append(task)
    # start threads
    for thread in threads:
        thread.start()
    # wait for all threads to complete their work
    for thread in threads:
        thread.join()
    # delete threads
    del threads[:]
```

**Comment by s0md3v** [comment]
Looks like multiprocessing won't be of any use here as this isn't a CPU intensive task and is completely based on I/O.
I tried different approaches while building Photon and selected the one which was the most efficient (efficient doesn't mean fast).

Thanks for reminding me tho, I will see what can be done to improve the overall crawling speed.
