### ISSUE TITLE
Character handling

### ISSUE THREAD

**Issue by h888t** [s0md3v/Photon#7]
Traceback (most recent call last):
  File "photon.py", line 382, in <module>
    f.write(x + '\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 137: ordinal not in range(128)

Fix:
change f.write(x + '\n')
to f.write(x.encode('utf-8') + '\n')

**Comment by s0md3v** [comment]
Hi there!

Thanks for reporting the issue.
Instead of encoding everything to `utf-8`, I declared the encoding with `# -*- coding: utf-8 -*-` which fixed the issue on my end.

Can you please verify the patch?
