### ISSUE TITLE
[Multiple Suggestions]

### ISSUE THREAD

**Issue by 0xInfection** [s0md3v/Photon#76]
Okay so I was going through the Photon library and I found some areas of improvements.
- [ ] Let photon be just a powerful crawler. Adding a option like `--plugin <name of plugin> / --plugin=<name of plugin>` is a good idea. Why?
        • It will make it easier for users to run custom plugins which they might have developed on their own. 
        • Think what bloat + heck it will be adding custom arguments for each plugin developed `like if there are 100 plugins, will you serve 100 arguments? One for each plugin? Sick idea isn't it?`
        • Make it something similar to the Nmap Scripting Engine. Your basic work is extensive crawling, but custom plugins help it to extend features.
- [ ] Add guidelines for custom plugin development which will can be used with photon without any changes in main code.
- [ ] Include `exporter` as a part of main build, not as a plugin. Plugins will be strictly restricted to extending features and enrichment of capabilities only.
- [x] Change the description of photon to a suitable one `Reconnaissance is way too broad for photon so far as the plugins available are concerned`.
- [x] Refer the url of the build badge to Travis CI where the build is being maintained (it currently points to commits history).
- [x] Add a verbose mode `-v/--verbose` for photon. Sometimes just that small output of what it has crawled doesn't satisfy. `I have done it!`

**Comment by s0md3v** [comment]
Dynamic plugin loading will be implemented if the number of plugins exceeds at least 10. It will be an overkill otherwise.
Closing this for now.
