### ISSUE TITLE
get_lfd

### ISSUE THREAD

**Issue by psychomad** [s0md3v/Photon#78]
Hi
After using the option --update i get this error:

Traceback (most recent call last):
  File "photon.py", line 187, in <module>
    domain = topLevel(main_url)
  File "photon.py", line 182, in topLevel
    toplevel = tld.get_fld(host, fix_protocol=True)
AttributeError: 'module' object has no attribute 'get_fld'

Any clue?
I installed also on another system and still the same
change target: same
delete totally and clone again: same

OS Kali3
Thanks

**Comment by s0md3v** [comment]
It works fine from here.

It would be great if you can provide me the target if possible so I can try to reproduce the issue.
If you have privacy concerns, you may want to dm me on twitter [@s0md3v](https://twitter.com/s0md3v)

However I don't think this issue is target specific. Please follow the [guidlines](https://github.com/s0md3v/Photon/wiki/Guidelines) for raising an issue in the best way possible.

**Comment by s0md3v** [comment]
Works as intended on my machine with a fresh clone.
![screenshot_2018-09-09_17-07-38](https://user-images.githubusercontent.com/26716802/45264022-e52c3e00-b452-11e8-9857-25a4cf0bcdc1.png)

**Comment by psychomad** [comment]
So i have to check somewhere else the caus eof the problem, thanks a lot!

**Comment by s0md3v** [comment]
Enter `python` in terminal. Following screen should appear
```
Python 2.7.15 (default, Jul 28 2018, 11:29:29) 
[GCC 8.1.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```
Enter the following command and let me know the output:
```
from tld import get_fld
```

**Comment by psychomad** [comment]
I discovered the real problem and i need to patch once for all... I got python2 and 3  and even if i specify python3  automatically choose the wrong version, even pip3. So i need to clean all the mess about pointing the correct release.
Anyway something strange with python and python3 shell if i write from tld import get_fld
i got: 

>>> from tld import get_fld
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'get_fld'

But now Photon works fine... (really im going crazy ahhaah)

**Comment by s0md3v** [comment]
Good luck and I am relieved that it has nothing to do with Photon.
