### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by fabaff** [s0md3v/Photon#99]
As mentioned already in #98 is the `setup.py` file missing in the repo.

If there is one around then I would like to suggest that `install_requires` and `entry_points` is added.

If `entry_points` one could launch Photon with `photon` without caring about the interpreter.

It looks like that it would require some changes in `photon.py` for the access of at least `user-agents.txt`.

```python
else:
    here = os.path.abspath(os.path.dirname(__file__))
    with open('{}/core/user-agents.txt'.format(here), 'r') as uas:
        user_agents = [agent.strip('\n') for agent in uas]
```

**Comment by s0md3v** [comment]
Hi @fabaff ,

You have contributed a lot already, would you mind submitting a PR for adding a setup.py?
I don't have much experience with that and I am afraid that I will mess up again.

Thanks ^_^

**Comment by fabaff** [comment]
Hmm, why was this closed?

**Comment by s0md3v** [comment]
[ inactivity ]
